# This is a basic workflow that is manually triggered

name: Minify JS

on:
  push:
    branches: [ actionsTest, main ]

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Minify Action
        run: |
          npm install terser --global
          terser dist/SocketApi.js -o dist/SocketApi.min.js
          
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}        
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add dist/SocketApi.min.js
          git commit -m "Minified version added"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
